### ISSUE TITLE
Code example of max30100

### ISSUE THREAD

**Issue by SloMusti** [GliaX/pulseox#21]
An example of code for processing measurement values: https://morf.lv/implementing-pulse-oximeter-using-max30100

**Comment by tareko** [comment]
Excellent. out of curiosity, did you find that on hackaday or somewhere else? I have looked at this chip, and it features in an alternative design by @cfalc. However, it uses reflective rather than transmission pulse oximetry, and also doesn't seem able to add more LEDs. The explanation of how, though, is definitely applicable..

tarek : )

**Comment by SloMusti** [comment]
Yes, have seen it on Hackaday. This is mainly useful to get more ideas about data processing required.
