### ISSUE TITLE
pulse oximeter circuit

### ISSUE THREAD

**Issue by VojislavM** [GliaX/pulseox#24]
why not use integrated pulse oximeter instade of IR LEDs and receiver?

**Comment by tareko** [comment]
Such as the MAX30100? @CFalc is working on [a model that uses an integrated chip](https://github.com/CFalc/Make-your-own-Pulse-Oximeter) which we'll also probably test. It's arduino-based and failed with LED / receiver combo in [its original iteration](https://github.com/GliaX/oximeter).

In response to the question of why *this* model doesn't use it, the main reason is that we want to add several more LEDs in the future to cover carboxyhemoglobin and methemoglobin. The current market offering [uses 8 LEDs to accomplish this](http://www.masimo.com/home/rainbow-pulse-co-oximetry/technology-overview/), but it can probably be done with 4 or so, which is why this model has several open spots for more LEDs.

**Comment by VojislavM** [comment]
Thank you for the explanation.
